In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<font size ='5' color='black'>ch.11 데이터프레임과 시리즈</font>
- pip install pandas (아나콘다 프롬포트)

# 1. 판다스 패키지
- 데이터 분석을 위해 반드시 알아야할 패키지.
- 넘파이를 기반으로 하며, 다른 많은 라이브러리와 잘 통합되도록 설계됨.
<br>
- 1차원 구조 시리즈, 2차원 구조 데이터프레임 제공.
<br>
- 장점
```
데이터 프레임 생성 용이, 파일 i/o 간편화, 레이블링
부분 데이터 추출, 크기 변경(행/열 삽입 및 삭제 용이)
데이터 분할 및 병합, 데이터 정렬, 결측치 처리, 피벗/언피벗 용이
```

**참조**

판다스 독스 : [Pandas Docs.](https://pandas.pydata.org/docs/)
판다스 API 레퍼런스 : [Pandas API ref.](https://pandas.pydata.org/docs/reference/index.html)

In [6]:
import pandas as pd

pd.__version__

'1.5.3'

In [9]:
#pd.read() : 'encoding=' 기본값 : utf-8
data = pd.read_json('data/ch09_member1.json')
display(data)
print(type(data))

  name  age    email   address job
0  홍길동   20  h@h.com   서울시 관악구   -
1  신길동   40  s@h.com  서울시 영등포구  팀장
2  김길동   30  k@h.com   서울시 동작구   -

<class 'pandas.core.frame.DataFrame'>

In [16]:
# 헤더가 있는 CSV
member3 = pd.read_csv('data/ch09_member3.csv')
member3

  name  age    email   address  job
0  홍길동   20  h@h.com   서울시 관악구  NaN
1  신길동   40  s@h.com  서울시 영등포구   팀장
2  김길동   30  k@h.com   서울시 동작구  NaN

In [17]:
# 헤더가 없는 CSV ; 헤더 설정 가능
member1 = pd.read_csv('data/ch09_member1.csv', 
                    header=None,
                    names=['이름', '나이', '이메일', '주소'] 
                     ) 
member1

    이름  나이               이메일        주소
0  홍길동  20  kildong@hong.com   서울시 관악구
1  김길동  40  kimdong@hong.com  서울시 영등포구
2  신길동  30  sindong@hong.com   서울시 동작구

In [18]:
pd.read_hdf('data/ch09_iris.h5', key='iris')

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# 2. 데이터 프레임 생성

## 2.1 딕셔너리를 이용한 데이터 프레임 생성

In [22]:
d = {'kor':[100,90], 'mat':[95,97]}
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   95
1   90   97

In [26]:
# 데이터 프레임을 딕셔너리로
df.to_dict()

{'kor': {0: 100, 1: 90}, 'mat': {0: 95, 1: 97}}

In [27]:
# 데이터 프레임을 넘파이 배열으로
df.to_numpy()

array([[100,  95],
       [ 90,  97]], dtype=int64)

In [29]:
# 데이터 프레임은 열별로 동일 자료형을 가짐
d = [{'kor':100, 'mat':95},
    {'kor':90, 'mat':97.5}]
df = pd.DataFrame(d)
df

   kor   mat
0  100  95.0
1   90  97.5

In [32]:
# 데이터 프레임의 열별 타입
print(df.dtypes)
print()
# 데이터 프레임의 정보 확인
df.info()

kor      int64
mat    float64
dtype: object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      float64
dtypes: float64(1), int64(1)
memory usage: 160.0 bytes

In [34]:
# 1차원 데이터 : 시리즈
type(df['kor'])

pandas.core.series.Series

In [35]:
# 데이터 프레임의 열 타입 변경
import numpy as np
df['kor'].astype(np.float64)

0    100.0
1     90.0
Name: kor, dtype: float64

In [36]:
# 열 인덱스에 맞추어 생성 및 결측치 처리
d = [{'kor':100, 'mat':100},{'kor':90, 'mat':95},{'kor':83,'eng':97}]
df = pd.DataFrame(d)
df

   kor    mat   eng
0  100  100.0   NaN
1   90   95.0   NaN
2   83    NaN  97.0

In [37]:
# 결측치의 type : float, 결측치가 있는 열은 float으로 처리됨
type(np.nan)

float

In [39]:
# 결측치는 int로 형변환이 불가함
df['mat'].astype('int32')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

## 2.2 리스트를 이용한 데이터 프레임 생성

In [41]:
kor = [100,100,95,80,87]
mat = [80,90,65,80,75]
df = pd.DataFrame({'kor':kor, 'mat':mat})
df

   kor  mat
0  100   80
1  100   90
2   95   65
3   80   80
4   87   75

In [44]:
# 두 리스트를 np.c_처리하여 데이터 프레임 생성 및 columns를 통해 헤더 생성
pd.DataFrame(np.c_[kor, mat], columns=['kor', 'mat'])

   kor  mat
0  100   80
1  100   90
2   95   65
3   80   80
4   87   75

In [47]:
l = [[100, 90],[70, 80]]
pd.DataFrame(l, index=['철수', '영희'], columns=['국어','수학'])

     국어  수학
철수  100  90
영희   70  80

- data.go.kr : '상가 상권 정보' 다운로드 - '민간 아파트 분양 가격' 다운로드

In [50]:
%ls "C:/ai/downloads/shareData/상가정보/"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 0C81-36F7

 C:\ai\downloads\shareData\상가정보 디렉터리

2026-07-08  오후 12:07    <DIR>          .
2026-07-14  오후 05:46    <DIR>          ..
2025-11-03  오전 12:45             1,011 [필독]파일열람방법.txt
2026-04-27  오전 11:10        61,321,696 소상공인시장진흥공단_상가(상권)정보_강원_202603.csv
2026-04-27  오전 11:10       367,852,181 소상공인시장진흥공단_상가(상권)정보_경기_202603.csv
2026-04-27  오전 11:10        92,474,293 소상공인시장진흥공단_상가(상권)정보_경남_202603.csv
2026-04-27  오전 11:10        76,309,810 소상공인시장진흥공단_상가(상권)정보_경북_202603.csv
2026-04-27  오전 11:10        40,031,721 소상공인시장진흥공단_상가(상권)정보_광주_202603.csv
2026-04-27  오전 11:10        61,825,564 소상공인시장진흥공단_상가(상권)정보_대구_202603.csv
2026-04-27  오전 11:10        41,866,930 소상공인시장진흥공단_상가(상권)정보_대전_202603.csv
2026-04-27  오전 11:10        84,329,596 소상공인시장진흥공단_상가(상권)정보_부산_202603.csv
2026-04-27  오전 11:10       292,646,735 소상공인시장진흥공단_상가(상권)정보_서울_202603.csv
2026-04-27  오전 11:10         9,651,297 소상공인시장진흥공단_상가(상권)정보_세종_202603.csv
2026-04-27  오전 11:10        28,285,232 소상공인시장진흥공단_상가(상권)정보_울산_202603.csv
2026-04-27  오전 11:10        74,007,608 소상공인시장진흥공단_상가(상권)정보_인천_202603.csv
2026-04-27  오전 11:10        53,165,985 소상공인시장진흥공단_상가(상권)정보_전남_202603.csv
2026-04-27  오전 11:10        56,632,709 소상공인시장진흥공단_상가(상권)정보_전북_202603.csv
2026-04-27  오전 11:10        32,746,698 소상공인시장진흥공단_상가(상권)정보_제주_202603.csv
2026-04-27  오전 11:10        66,764,669 소상공인시장진흥공단_상가(상권)정보_충남_202603.csv
2026-04-27  오전 11:10        50,941,247 소상공인시장진흥공단_상가(상권)정보_충북_202603.csv
              18개 파일       1,490,854,982 바이트
               2개 디렉터리  145,154,404,352 바이트 남음

In [56]:
df = pd.read_csv(r'C:/ai/downloads/shareData/상가정보/소상공인시장진흥공단_상가(상권)정보_세종_202603.csv',
                #encoding='utf-8', sep=',' : 기본값
                nrows = 30, # 첫 30행 불러오기
                low_memory=False, # 데이터 용량이 클 경우 사용
                )
df.shape # 데이터 프레임 크기

(30, 39)

In [55]:
df.head(1) # 상위 1행

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220813963449,레인카페,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,4473025021101010001038753,NaN,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,339883.0,30027,NaN,지,NaN,127.300453,36.600906

In [60]:
# 데이터 프레임 디스플레이 옵션
pd.options.display.max_columns = 40 # 40열까지 display
pd.options.display.max_rows = 40 # 40행까지 display

In [63]:
df.head(3).T # 상위 3행을 전치

,0,1,2
상가업소번호,MA010120220813963449,MA010120220805872513,MA010120220700019175
상호명,레인카페,수와마을,세종수이비인후과의원
지점명,NaN,NaN,NaN
상권업종대분류코드,I2,I2,Q1
상권업종대분류명,음식,음식,보건의료
상권업종중분류코드,I212,I201,Q102
상권업종중분류명,비알코올,한식,의원
상권업종소분류코드,I21201,I20101,Q10201
상권업종소분류명,카페,백반/한정식,내과/소아과 의원
표준산업분류코드,I56229,I56111,Q86201
표준산업분류명,기타 비알코올 음료점업,한식 일반 음식점업,일반의원
시도코드,36,36,36
시도명,세종특별자치시,세종특별자치시,세종특별자치시
시군구코드,36110,36110,36110
시군구명,세종특별자치시,세종특별자치시,세종특별자치시
행정동코드,36110250,36110250,36110525
행정동명,조치원읍,조치원읍,해밀동
법정동코드,3611025021,3611025030,3611011600
법정동명,조치원읍,조치원읍,해밀동
지번코드,3611025021101010001,3611025030103790016,3611011600200050002
대지구분코드,1,1,2
대지구분명,대지,대지,산
지번본번지,101,379,5
지번부번지,1.0,16.0,2.0
지번주소,세종특별자치시 세종특별자치시 조치원읍 원리 101-1,세종특별자치시 세종특별자치시 조치원읍 죽림리 379-16,세종특별자치시 세종특별자치시 해밀동 산 5-2
도로명코드,361104574473,361103258034,361103352828
도로명,세종특별자치시 세종특별자치시 조치원읍 조치원8길,세종특별자치시 세종특별자치시 조치원읍 충현로,세종특별자치시 세종특별자치시 해밀3로
건물본번지,16,75,43
건물부번지,NaN,1.0,NaN
건물관리번호,4473025021101010001038753,4473025030103790016042253,3611011600200050002000001
건물명,NaN,NaN,행정중심복합도시
도로명주소,세종특별자치시 세종특별자치시 조치원읍 조치원8길 16,세종특별자치시 세종특별자치시 조치원읍 충현로 75-1,세종특별자치시 세종특별자치시 해밀3로 43
구우편번호,339883.0,339884.0,NaN
신우편번호,30027,30034,30092
동정보,NaN,NaN,NaN
층정보,지,NaN,NaN
호정보,NaN,NaN,NaN
경도,127.300453,127.296263,127.264487
위도,36.600906,36.595303,36.528585